name: DEBUG DETECTIVE

on: workflow_dispatch # Lancement manuel seulement

jobs:
  troubleshoot:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Récupération des fichiers
        uses: actions/checkout@v3

      - name: 2. AFFICHER LA LISTE DES FICHIERS (Regarde ici)
        run: |
          echo "=== LISTE DES FICHIERS A LA RACINE ==="
          ls -la
          echo "======================================"

      - name: 3. Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 4. Installation des librairies (Force)
        run: pip install requests beautifulsoup4 lxml

      - name: 5. Tentative de lancement (main.py)
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
        
