name: YouTube Bot

on:
  schedule:
    - cron: '*/10 * * * *' # Toutes les 10 minutes
  workflow_dispatch: # Bouton manuel pour tester

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation des librairies
        run: |
          pip install -r requirements.txt

      - name: Lancement du Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Sauvegarde mémoire
        run: |
          git config --global user.name 'GitHub Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add last_videos.txt
          git commit -m "Auto-update" || echo "Rien a changer"
          git push
          git config --global user.email 'bot@noreply.github.com'
          git add last_videos.txt
          # La ligne magique ci-dessous empêche le crash si rien n'a changé
          git commit -m "Auto-update memory" || echo "Aucun changement à sauvegarder"
          git push
