name: Check YouTube Fast

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

# --- AJOUTE CES 3 LIGNES ICI ---
permissions:
  contents: write
# ------------------------------

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Ajoute ceci pour être sûr que le push fonctionne
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml

      - name: Run YouTube Tracker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python youtube_tracker.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # On vérifie si le fichier existe pour éviter une erreur
          touch last_videos.txt 
          git add last_videos.txt
          git commit -m "Update last videos log" || exit 0
          git push
